=== HoangKien-dream/DOM_SAX/users.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" type="user" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:group name="group-name">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
            <xs:element name="age">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="120"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:complexType name="employeeInfor">
        <xs:sequence>
            <xs:group ref="group-name"/>
            <xs:element name="position" type="xs:string"/>
            <xs:element name="department" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="teacherInfor">
        <xs:sequence>
            <xs:group ref="group-name"/>
            <xs:element name="experience" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="user">
        <xs:choice>
            <xs:element name="teacher" type="teacherInfor"/>
            <xs:element name="employee" type="employeeInfor"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== HoangKien-dream/DOM_SAX/users.xml
<?xml version="1.0" encoding="UTF-8"?>

<users
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="users.xsd" xmlns="https://www.w3schools.com">
    <user>
        <employee id="1">
            <firstName>Hoàng</firstName>
            <lastName>Kiên</lastName>
            <email>hoangkien@gmail.com</email>
            <phone>0964866701</phone>
            <age>20</age>
            <position>Boss</position>
            <department>MNSĐ</department>
        </employee>
    </user>
    <user>
        <teacher id="2">
            <firstName>Minh</firstName>
            <lastName>Thu</lastName>
            <email>minhthu@gmail.com</email>
            <phone>0964866702</phone>
            <age>25</age>
            <experience>15</experience>
        </teacher>
    </user>
    <user>
        <teacher id="3">
            <firstName>Minh</firstName>
            <lastName>Thu</lastName>
            <email>minhthu@gmail.com</email>
            <phone>0964866702</phone>
            <age>25</age>
            <experience>15</experience>
        </teacher>
    </user>
    <user>
        <teacher id="4">
            <firstName>Thanh</firstName>
            <lastName>Mai</lastName>
            <email>thanhmai@gmail.com</email>
            <phone>0964866702</phone>
            <age>10</age>
            <experience>5</experience>
        </teacher>
    </user>
    <user>
        <employee id="5">
            <firstName>Luka</firstName>
            <lastName>Chim</lastName>
            <email>lukaku@gmail.com</email>
            <phone>0964866701</phone>
            <age>28</age>
            <position>St</position>
            <department>Chelsea</department>
        </employee>
    </user>
</users>
